### ISSUE TITLE
basis_link file is not accessible

### ISSUE THREAD

**Issue by mmagithub** [merzlab/QUICK-docs#20]
Hi,
I am trying to run a qm/mm calculation with the amber/quick interface.
##########
&cntrl
 imin=0, irest=1, ntx=5,
 nstlim=1000, dt=0.001,
 ntpr=10, ntwx=10, ioutfm=1, ntwr=100,
 ntf = 2, ntc = 2, tol = 0.0000005,
 ntb=0, cut=10,
 ntt=1, tautp=4.0, temp0=300.0,
 ifqnt=1,
/
&qmmm   
iqmatoms=:32
 qmcharge=1,
 qmshake=0,
 qmcut=10,
 qm_theory = 'extern',
 printdipole=1,
 writepdb=1,
 qm_pme=1,
 qm_ewald = 0,
/
&quick
method='PBE0',
basis='6-31+G*',
executable='quick.cuda',
/
``
###########
It seems that quick binaries cannot see the basis set files, and I got these errors:
#######
| Error: basis_link file is not accessible.

 Check if QUICK_BASIS environment variable is set.
###############

I attempted to set up environmental variable in the &quick section in the sander qm/mm file, but in vain ?

Any clue?

Thanks,
Marawan

**Comment by merzlab** [comment]
Hi Marawan, 

Did you source amber.sh before running the calculation? It should set the QUICK_BASIS environment variable; but you can also source quick.rc file located in AMBERHOME directory. Make sure to run “echo $QUICK_BASIS” in bash terminal and check the value of the variable before running the calculation. Let me know if the problem still persists. 

Best regards,
Madu Manathunga

**Comment by mmagithub** [comment]
Thanks Madu. True, sourcing (~/QUICK-master/quick_dir/quick.rc) solved the issue.
Although other calculation issues popped up, I will see and I will post questions if I have them,

Wonderful tool,

Thanks,
Marawan

**Comment by merzlab** [comment]
Great! You are welcome. 

Best regards,
Madu

**Comment by agoetz** [comment]
@Madu86 Can we close this issue? It seems resolved.

**Comment by Madu86** [comment]
Yes, I am closing this issue.
